version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/tests"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
